export {
  createProductSchema,
  updateProductSchema,
  productFilterSchema,
  type CreateProductInput,
  type UpdateProductInput,
  type ProductFilterInput,
  type PaginatedProductItem,
  type PaginatedProductsResult,
  type PaginatedProductsInput,
  type RelatedProduct,
  LOW_STOCK_THRESHOLD,
  type LowStockProduct,
  type SendEmailFn,
  buildLowStockEmailHtml,
  type RecommendedProduct,
  type VariantOption,
  type VariantOptionValue,
  type VariantCombination,
  type ProductVariantInfo,
  type ProductVariantsData,
  type CreateProductVariantInput,
  type CreateVariantOptionInput,
} from "./types";

export {
  createProduct,
  updateProduct,
  getProduct,
  getProductBySlug,
  listProducts,
  countProducts,
  getProductsPaginated,
  deleteProduct,
  getRelatedProducts,
  getFrequentlyBoughtTogether,
  getPopularInCategory,
  getTrendingProducts,
  getRandomActiveCategory,
  getLowStockProducts,
  sendLowStockAlertEmails,
  getProductVariants,
  createProductVariant,
  createVariantOption,
} from "./actions";

export {
  getBundleBySlug,
  getActiveBundles,
  getBundlesForProduct,
  calculateBundlePrice,
  type Bundle,
  type BundleItem,
  type BundleProduct,
  type BundlePriceInfo,
  type BundleWithPrice,
} from "./bundle-actions";
