export {
  createProductSchema,
  updateProductSchema,
  productFilterSchema,
  type CreateProductInput,
  type UpdateProductInput,
  type ProductFilterInput,
} from "./types";

export {
  createProduct,
  updateProduct,
  getProduct,
  getProductBySlug,
  listProducts,
  countProducts,
  getProductsPaginated,
  deleteProduct,
  getRelatedProducts,
  getLowStockProducts,
  sendLowStockAlertEmails,
  buildLowStockEmailHtml,
  LOW_STOCK_THRESHOLD,
  type RelatedProduct,
  type LowStockProduct,
  type SendEmailFn,
  type PaginatedProductItem,
  type PaginatedProductsResult,
  type PaginatedProductsInput,
} from "./actions";
